import { test, expect } from '@playwright/test';
import { defaults } from '../../src/model.js';
async function seed(page) {
  const config = defaults(); Object.assign(config.grid, { nx: 8, ny: 8, preset: 'open', minDepth: 40, maxDepth: 100, edits: { 27: 0 } });
  Object.assign(config.numerics, { dt: 1, maxSteps: 10, steadyWindow: 10, outputInterval: 2 });
  await page.goto('/'); await page.evaluate(config => localStorage.setItem('webroms.project.v1', JSON.stringify(config)), config); await page.reload();
}
test('seven stages, coastal rivers, initial climate, zoom and real export', async ({ page }) => {
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await seed(page);
  await expect(page.locator('.steps button')).toHaveCount(7);
  await expect(page.locator('#openTerrainDialog')).toHaveCount(0);
  const terrainDownload = page.waitForEvent('download'); await page.locator('#terrainDownload').click();
  const downloaded = await terrainDownload; expect(downloaded.suggestedFilename()).toBe('webroms-terrain.zip');
  await page.locator('#terrainImport').setInputFiles(await downloaded.path());
  await expect(page.locator('#toast')).toContainText('読み込みました');
  await page.locator('[data-view="map"]').click();
  await page.locator('#riverBrush').selectOption('river-add');
  const rect = await page.locator('#mapCanvas').boundingBox();
  const mapSize = Math.min(rect.width - 104, rect.height - 104);
  await page.mouse.click(rect.x + rect.width / 2 - mapSize / 16, rect.y + rect.height / 2 + mapSize / 16);
  await page.locator('[data-step="4"]').click();
  const c = await page.evaluate(() => JSON.parse(localStorage.getItem('webroms.project.v1')));
  expect(c.rivers).toHaveLength(1); expect(c.rivers[0].landCell).toBe(27);
  await expect(page.getByLabel('流量', { exact: true })).toBeVisible();
  await page.locator('[data-step="0"]').click();
  await page.getByLabel('地形の種類').selectOption('osaka');
  await page.locator('[data-step="2"]').click();
  await page.getByLabel('初期分布', { exact: true }).selectOption('regional-summer');
  await expect(page.locator('#settingsForm')).toContainText('日本太平洋側');
  await page.locator('#sliceRow').fill('2');
  const before = await page.locator('#sectionCanvas').evaluate(c => c.toDataURL());
  await page.locator('#sectionZoomIn').click();
  expect(await page.locator('#sectionCanvas').evaluate(c => c.toDataURL())).not.toEqual(before);
  await page.screenshot({ path: 'test-results/seven-initial.png', fullPage: true });
  await page.locator('[data-step="3"]').click();
  await expect(page.locator('option[value="radiation"]')).toHaveCount(0);
  await page.locator('.boundary-baseline summary').click();
  await page.locator('input[data-path="boundary.west.layers.2.temp"]').fill('24');
  await page.locator('input[data-path="boundary.west.layers.2.temp"]').blur();
  const edited = await page.evaluate(() => JSON.parse(localStorage.getItem('webroms.project.v1')).boundary.west);
  expect(edited.layers[2].temp).toBe(24); expect(edited.painted.temp[2]).toBeFalsy(); expect(edited.fromInitial).toBe(false);
  await page.getByLabel('境界形式').selectOption('closed');
  await page.screenshot({ path: 'test-results/seven-closed.png', fullPage: true });
  await page.locator('[data-step="6"]').click();
  await expect(page.locator('.step-actions #calculateButton')).toBeVisible();
  await page.locator('#calculateButton').click();
  await expect(page.locator('#runLog')).toContainText('ROMS: DONE', { timeout: 60000 });
  await page.locator('#resultButton').click();
  await page.locator('#exportInterval').fill('2');
  const output = page.waitForEvent('download'); await page.locator('#downloadResults').click();
  const nc = await output; expect(nc.suggestedFilename()).toBe('webroms-results.nc');
  await page.locator('#exportFormat').selectOption('shape');
  const shapeOutput = page.waitForEvent('download'); await page.locator('#downloadResults').click();
  expect((await shapeOutput).suggestedFilename()).toBe('webroms-results.zip');
  await page.locator('#closeResults').click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'test-results/seven-mobile.png', fullPage: true });
  expect(errors).toEqual([]);
});

test('NOAA-derived biological fields run offline and tides expose API status', async ({ page }) => {
  await page.route('https://api.tidesandcurrents.noaa.gov/**', route => route.fulfill({ json: { predictions: [{ t: '2026-01-01 00:00', v: '0.5' }, { t: '2026-01-01 01:00', v: '-0.2' }] } }));
  await seed(page);
  await page.getByLabel('地形の種類').selectOption('japan');
  await page.locator('[data-step="1"]').click();
  await page.getByLabel('生態系の計算').selectOption('true');
  await page.locator('[data-step="2"]').click();
  await page.getByLabel('初期分布', { exact: true }).selectOption('regional-winter');
  await page.getByLabel('生物濃度の初期分布').selectOption('climatology');
  await expect(page.locator('#validation')).not.toContainText('不正');
  await page.locator('[data-step="3"]').click();
  await page.locator('.advanced-settings summary').click();
  await page.locator('#tideStation').fill('9414290');
  await page.locator('#tideStart').fill('2026-01-01');
  await page.locator('#fetchTides').click();
  await expect(page.locator('#tideStatus')).toContainText('潮差0.70 m');
  await page.locator('[data-step="6"]').click();
  await page.locator('#calculateButton').click();
  await expect(page.locator('#runLog')).toContainText('ROMS: DONE');
});
