import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';

const endpoint = 'https://oceanwatch.pifsc.noaa.gov/erddap/griddap/ETOPO_2022_v1_15s.json';
const regions = {
  setouchi: [130.8, 135.6, 33.1, 34.9],
  osaka: [134.7, 135.6, 34, 34.85], tokyo: [139.5, 140.25, 34.9, 35.75],
  ise: [136.5, 137.4, 34.35, 35.15], japan: [128, 148, 28, 46],
  california: [225, 245, 25, 50], 'north-pacific': [120, 260, 0, 65],
  'south-pacific': [140, 295, -60, 0], 'north-atlantic': [260, 375, 0, 65],
  'south-atlantic': [290, 385, -60, 0]
};
const sha = bytes => createHash('sha256').update(bytes).digest('hex');
const cache = new URL('../.tools/terrain/', import.meta.url);
await mkdir(cache, { recursive: true });
const output = {};
for (const [id, [west, east, south, north]] of Object.entries(regions)) {
  const lonStart = Math.round(west * 240), lonEnd = Math.round(east * 240) - 1;
  const latStart = Math.round((south + 90) * 240), latEnd = Math.round((north + 90) * 240) - 1;
  const sx = Math.max(1, Math.ceil((lonEnd - lonStart) / 240));
  const sy = Math.max(1, Math.ceil((latEnd - latStart) / 200));
  const indices = Array.from({ length: Math.floor((lonEnd - lonStart) / sx) + 1 }, (_, i) => lonStart + i * sx);
  const sections = [indices.filter(i => i < 86400), indices.filter(i => i >= 86400)].filter(a => a.length);
  const rows = [], sources = [];
  for (let s = 0; s < sections.length; s++) {
    const a = sections[s], offset = a[0] >= 86400 ? 86400 : 0;
    const url = `${endpoint}?z[${latStart}:${sy}:${latEnd}][${a[0] - offset}:${sx}:${a.at(-1) - offset}]`;
    const file = new URL(`${id}-${s}.json`, cache);
    let bytes;
    try { bytes = await readFile(file); }
    catch {
      const response = await fetch(url, { signal: AbortSignal.timeout(120000) });
      if (!response.ok) throw new Error(`${id}: HTTP ${response.status}`);
      bytes = Buffer.from(await response.arrayBuffer());
      JSON.parse(bytes); await writeFile(file, bytes);
    }
    const table = JSON.parse(bytes).table;
    if (JSON.stringify(table?.columnNames) !== JSON.stringify(['latitude', 'longitude', 'z'])) throw new Error(`Invalid columns: ${id}`);
    for (const [lat, lon, z] of table.rows) {
      if (![lat, lon, z].every(Number.isFinite)) throw new Error(`Missing elevation: ${id}`);
      rows.push([lat, lon + offset / 240, z]);
    }
    sources.push({ url, sha256: sha(bytes) });
  }
  const latitudes = [...new Set(rows.map(r => r[0]))].sort((a, b) => a - b);
  const longitudes = [...new Set(rows.map(r => r[1]))].sort((a, b) => a - b);
  const width = longitudes.length, height = latitudes.length;
  if (rows.length !== width * height) throw new Error(`Incomplete grid: ${id}`);
  const xs = new Map(longitudes.map((x, i) => [x, i])), ys = new Map(latitudes.map((y, i) => [y, i]));
  const elevation = new Array(width * height);
  for (const [lat, lon, z] of rows) elevation[ys.get(lat) * width + xs.get(lon)] = Math.round(z);
  output[id] = { width, height, bounds: { west: longitudes[0], east: longitudes.at(-1), south: latitudes[0], north: latitudes.at(-1) }, stride: [sx, sy], sources, elevation };
  console.log(`${id}: ${width} x ${height}, ${sources.length} source subset(s)`);
}
const payload = JSON.stringify(output);
await writeFile(new URL('../src/data/terrain-etopo2022.js', import.meta.url),
  '// Generated by scripts/fetch-terrain.mjs. NOAA ETOPO 2022, CC0. South-to-north row order.\n' +
  `export const TERRAIN_DATA_SHA256 = '${sha(payload)}';\nexport const TERRAIN_DATA = ${payload};\n`);
