set(CMAKE_SYSTEM_NAME Emscripten)
set(CMAKE_SYSTEM_PROCESSOR wasm32)
set(CMAKE_C_COMPILER /opt/emsdk/upstream/emscripten/emcc)
set(CMAKE_CXX_COMPILER /opt/emsdk/upstream/emscripten/em++)
set(CMAKE_Fortran_COMPILER /opt/flang/host/bin/flang)
set(CMAKE_Fortran_FLAGS_INIT "--target=wasm32-unknown-emscripten -O2")
set(CMAKE_AR /opt/emsdk/upstream/emscripten/emar)
set(CMAKE_RANLIB /opt/emsdk/upstream/emscripten/emranlib)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_Fortran_COMPILER_WORKS TRUE)
set(CMAKE_CROSSCOMPILING_EMULATOR /opt/emsdk/node/22.16.0_64bit/bin/node)
